name: Angular Build

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Angular Build
    if: "! github.event.pull_request.draft"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Install dependencies
        run: npm install

      - name: Build Checker
        run: npm run build
